name: Blah

on: push

jobs:
  job1:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v2
      - run: echo $GITHUB_CONTEXT
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
      - uses: dwieeb/get-changed-files@5a87587
        id: files
        if: ${{ github.event_name != 'push' || github.event.before != '0000000000000000000000000000000000000000' }}
        with:
          format: 'json'
      - run: echo $DATA
        env:
          DATA: ${{ steps.files.outputs.all }}
      - run: echo "Do the thing"
        if: ${{ steps.files.outputs.all }}
